schema_version: 1

context:
  name: ipy
  version: "1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c145e664e84642fac875a043fab1a0b50bd65297385dc438dbfe25f24e65ac61

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - IPy
      python_version: ["${{ python_min }}.*", "3.*"]
      pip_check: true

about:
  summary: Class and tools for handling of IPv4 and IPv6 addresses and networks
  license: BSD-3-Clause
  license_file: COPYING
  homepage: https://github.com/autocracy/python-ipy
  repository: https://github.com/autocracy/python-ipy

extra:
  recipe-maintainers:
    - beenje
